version: '3.3'

services:
  # drupal:
  #   image: drupal:9
  #   user: root
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./web:/var/www/html
  #   restart: always
  #   depends_on:
  #     - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=events_org
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8090:80
    environment:  
      PMA_HOST: mysql  
    depends_on: 
      - mysql

volumes:
  web:
  db_data: